bootstrap_servers="localhost:9092"
consumer_gid="NearlineSupervisedRecommendationGenerator"
postgres_db_uri="postgresql+psycopg2://subho:souvik@localhost:5432/nearline_supervised_recommendation_generator_db"