bootstrap_servers="localhost:9092"
feature_vector_consumer_gid="NearlineSupervisedRecommendationTrainer"
postgres_db_uri="postgresql+psycopg2://subho:souvik@localhost:5432/nearline_supervised_recommendation_trainer_db"